=== rbisdorff/Digraph3/Digraph3/branches/Digraph2/test/digraphs.dtd
<!ELEMENT node (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ELEMENT v (#PCDATA)>
<!ELEMENT nodes (node*)>
<!ELEMENT arc (i,t,v)>
<!ELEMENT valuationdomain (min,max)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT relation (arc*)>
<!ELEMENT header (name,author,reference)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT reference (#PCDATA)>
<!ELEMENT digraph (header,nodes,valuationdomain,relation)>

<!ELEMENT scale (min,max)>
<!ELEMENT indifference (#PCDATA)>
<!ELEMENT preference (#PCDATA)>
<!ELEMENT weakveto (#PCDATA)>
<!ELEMENT veto (#PCDATA)>
<!ELEMENT thresholds (indifference,preference,weakveto,veto)>
<!ELEMENT critname (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT criterion (critname,scale,thresholds,weight)>
<!ELEMENT criteria (criterion*)>
<!ELEMENT actions (action*)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT evaluations (evaluation*)>
<!ELEMENT evaluation (critname,evalactions*)>
<!ELEMENT evalactions (action,value)>
<!ELEMENT performancetableau (header,criteria,actions,evaluations)>

<!ATTLIST digraph 
      category CDATA "general" 
      subcategory CDATA "general">

<!ATTLIST performancetableau 
      category CDATA "standard" 
      subcategory CDATA "standard">

=== rbisdorff/Digraph3/Digraph3/branches/Digraph2/test/testdigraph.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="digraphs.xsl"?>
<!DOCTYPE digraph SYSTEM "digraphs.dtd">
<digraph category="general" subcategory="general">
<header>
<name>testdigraph.xml</name>
<author>R. Bisdorff</author>
<reference>test instance for general Digraph class.</reference>
</header><nodes>
<node>1</node>
<node>2</node>
<node>3</node>
<node>4</node>
<node>5</node>
</nodes>
<valuationdomain>
<min>-10</min>
<max>10</max>
</valuationdomain>
<relation>
<arc>
<i>1</i>
<t>1</t>
<v>-10</v>
</arc>
<arc>
<i>1</i>
<t>2</t>
<v>-10</v>
</arc>
<arc>
<i>1</i>
<t>3</t>
<v>-10</v>
</arc>
<arc>
<i>1</i>
<t>4</t>
<v>10</v>
</arc>
<arc>
<i>1</i>
<t>5</t>
<v>-10</v>
</arc>
<arc>
<i>2</i>
<t>1</t>
<v>-10</v>
</arc>
<arc>
<i>2</i>
<t>2</t>
<v>-10</v>
</arc>
<arc>
<i>2</i>
<t>3</t>
<v>10</v>
</arc>
<arc>
<i>2</i>
<t>4</t>
<v>-10</v>
</arc>
<arc>
<i>2</i>
<t>5</t>
<v>-10</v>
</arc>
<arc>
<i>3</i>
<t>1</t>
<v>-10</v>
</arc>
<arc>
<i>3</i>
<t>2</t>
<v>10</v>
</arc>
<arc>
<i>3</i>
<t>3</t>
<v>-10</v>
</arc>
<arc>
<i>3</i>
<t>4</t>
<v>-10</v>
</arc>
<arc>
<i>3</i>
<t>5</t>
<v>10</v>
</arc>
<arc>
<i>4</i>
<t>1</t>
<v>10</v>
</arc>
<arc>
<i>4</i>
<t>2</t>
<v>-10</v>
</arc>
<arc>
<i>4</i>
<t>3</t>
<v>10</v>
</arc>
<arc>
<i>4</i>
<t>4</t>
<v>-10</v>
</arc>
<arc>
<i>4</i>
<t>5</t>
<v>10</v>
</arc>
<arc>
<i>5</i>
<t>1</t>
<v>10</v>
</arc>
<arc>
<i>5</i>
<t>2</t>
<v>-10</v>
</arc>
<arc>
<i>5</i>
<t>3</t>
<v>10</v>
</arc>
<arc>
<i>5</i>
<t>4</t>
<v>-10</v>
</arc>
<arc>
<i>5</i>
<t>5</t>
<v>-10</v>
</arc>
</relation>
</digraph>

=== rbisdorff/Digraph3/Digraph3/test/testperftab.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="performanceTableau.xsl"?>

<!DOCTYPE digraph SYSTEM "digraphs.dtd">

<performancetableau category="test" subcategory="test">
	<header>
		<name>testperftab</name>
		<author>R. Bisdorff</author>
		<reference>test XML implementation</reference>
	</header>

	<criteria>
	  <criterion>

	    <critname>g1</critname>
	    <scale>
	      <min>0.0</min>
	      <max>1.0</max>
	    </scale>
	    <thresholds>
	      <indifference>0.1</indifference>
	      <preference>0.2</preference>
	      <weakveto>0.6</weakveto>
	      <veto>0.8</veto>
	    </thresholds>
	    <weight>1.0</weight>
	  </criterion>

	  <criterion>
	    <critname>g2</critname>
	    <scale>
	      <min>0.0</min>
	      <max>1.0</max>
	    </scale>
	    <thresholds>
	      <indifference>0.1</indifference>
	      <preference>0.2</preference>
	      <weakveto>0.6</weakveto>
	      <veto>0.8</veto>
	    </thresholds>
	    <weight>1.0</weight>
	  </criterion>
	  
	  <criterion>
	    <critname>g3</critname>
	    <scale>
	      <min>0.0</min>
	      <max>1.0</max>
	    </scale>
	    <thresholds>
	      <indifference>0.1</indifference>
	      <preference>0.2</preference>
	      <weakveto>0.6</weakveto>
	      <veto>0.8</veto>
	    </thresholds>
	    <weight>1.0</weight>
	  </criterion>
	</criteria>

	<actions>
	  <action>a1</action>
	  <action>a2</action>
	  <action>a3</action>
	</actions>

	<evaluations>
	  <evaluation>
	    <critname>g1</critname>
	    <evalactions>
	      <action>a1</action>
	      <value>0.5</value>
	    </evalactions>
	    <evalactions>
	      <action>a2</action>
	      <value>0.5</value>
	    </evalactions>
	    <evalactions>
	      <action>a3</action>
	      <value>0.5</value>
	    </evalactions>
	  </evaluation>

	  <evaluation>
	    <critname>g2</critname>
	    <evalactions>
	      <action>a1</action>
	      <value>0.5</value>
	    </evalactions>
	    <evalactions>
	      <action>a2</action>
	      <value>0.5</value>
	    </evalactions>
	    <evalactions>
	      <action>a3</action>
	      <value>0.5</value>
	    </evalactions>
	  </evaluation>

	  <evaluation>
	    <critname>g3</critname>
	    <evalactions>
	      <action>a1</action>
	      <value>0.5</value>
	    </evalactions>
	    <evalactions>
	      <action>a2</action>
	      <value>0.5</value>
	    </evalactions>
	    <evalactions>
	      <action>a3</action>
	      <value>0.5</value>
	    </evalactions>
	  </evaluation>
	</evaluations>

</performancetableau>
